language: node_js
node_js:
  - '14.15.4'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - 'yarn global add gatsby'
  - 'yarn'
script:
  - 'yarn lint'
  # - 'yarn test'
  # - 'yarn coveralls'
after_success:
  - 'yarn deploy'
