language: node_js
node_js:
  - '10.15.3'
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - 'yarn global add gatsby'
  - 'yarn'
script:
  - 'yarn test'
after_success:
  - 'yarn deploy'
